class Constants:
    INDEX_DIRECTORY = "my_index_directory"
    WIKI_DIRECTORY = "./FileExample/"
    REDIRECT_PREFIX = "#REDIRECT "
    HTTP_PREFIX = "http://www."
    HTTPS_PREFIX = "https://www."
    TPL_TAG = "tpl"
    REF_TAG = "ref"
    IMAGE_TAG = "[[Image:"
    FILE_TAG = "[[File:"
    CHAT_GPT_API_KEY = "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"
