class Constants:
    INDEX_DIRECTORY = "my_index_directory"
    QUESTIONS_FILE = "data/questions.txt"
    WIKI_DIRECTORY = "data/FileExample/"
    REDIRECT_PREFIX = "#REDIRECT "
    HTTP_PREFIX = "http://www."
    HTTPS_PREFIX = "https://www."
    TPL_TAG = "tpl"
    REF_TAG = "ref"
    IMAGE_TAG = "[[Image:"
    FILE_TAG = "[[File:"
    CHAT_GPT_API_KEY = ""
